[project]
name = "i23-cam-viewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cothread>=2.20.0",
    "opencv-python-headless>=4.11.0.86",
    "pyqt5>=5.15.11",
    "pyqtwebengine>=5.15.7",
]
